openapi: 3.0.3
info:
  version: 1.0.0
  title: ACME Explorer
  description: Projecto para la asignatura de Cloud Engineering 

security:
  - apikey: []
  
paths:
  /api/v1/actors: {$ref: resources/actor.yaml#/paths/api-v1-actors}
  /api/v1/actors/{_id}: {$ref: resources/actor.yaml#/paths/api-v1-actors-id}
  /api/v1/sponsorships: {$ref: resources/sponsorship.yaml#/paths/api-v1-sponsorships}
  /api/v1/sponsorships/{_id}: {$ref: resources/sponsorship.yaml#/paths/api-v1-sponsorships-id}
  /api/v1/trips: {$ref: resources/trip.yaml#/paths/api-v1-trips}
  /api/v1/trips/{ticker}: {$ref: resources/trip.yaml#/paths/api-v1-trips-ticker}
  /api/v1/applications: {$ref: resources/application.yaml#/paths/api-v1-applications}
  /api/v1/applications/{_id}: {$ref: resources/application.yaml#/paths/api-v1-applications-id}
  /api/v1/finders: {$ref: resources/finder.yaml#/paths/api-v1-finders}
  /api/v1/finders/{_id}: {$ref: resources/finder.yaml#/paths/api-v1-finders-id}

components:
  securitySchemes:
    apikey:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    actor: {$ref: resources/actor.yaml#/schemas/actor}
    sponsorship: {$ref: resources/sponsorship.yaml#/schemas/sponsorship}
    trip: {$ref: resources/trip.yaml#/schemas/trip}
    application: {$ref: resources/application.yaml#/schemas/application}
    finder: {$ref: resources/finder.yaml#/schemas/finder}
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
      additionalProperties: true