openapi: 3.0.3
info:
  version: 1.0.0
  title: ACME Explorer
  description: Projecto para la asignatura de Cloud Engineering 

paths:
  /api/v1/login: {$ref: resources/actor.yaml#/paths/api-v1-login}
  /api/v1/actors: {$ref: resources/actor.yaml#/paths/api-v1-actors}
  /api/v1/actors/{_id}: {$ref: resources/actor.yaml#/paths/api-v1-actors-id}
  /api/v2/actors/explorersInPeriod: {$ref: resources/actor.yaml#/paths/api-v2-actors-explorersInPeriod}
  /api/v2/actors/{_id}/moneyInPeriod: {$ref: resources/actor.yaml#/paths/api-v2-actors-id-moneyInPeriod}
  /api/v1/sponsorships: {$ref: resources/sponsorship.yaml#/paths/api-v1-sponsorships}
  /api/v1/sponsorships/{_id}: {$ref: resources/sponsorship.yaml#/paths/api-v1-sponsorships-id}
  /api/v1/sponsorships/{_id}/pay: {$ref: resources/sponsorship.yaml#/paths/api-v1-sponsorships-id-pay}
  /api/v1/trips: {$ref: resources/trip.yaml#/paths/api-v1-trips}
  /api/v1/trips/{_id}: {$ref: resources/trip.yaml#/paths/api-v1-trips-id}
  /api/v1/trips/{trip_id}/questions: {$ref: resources/trip.yaml#/paths/api-v1-trips-id-questions}
  /api/v2/trips/mine/questions: {$ref: resources/trip.yaml#/paths/api-v2-trips-mine-questions}
  /api/v1/trips/{trip_id}/questions/{question_id}: {$ref: resources/trip.yaml#/paths/api-v1-trips-id-questions-id}
  /api/v1/trips/{trip_id}/questions/{question_id}/reply: {$ref: resources/trip.yaml#/paths/api-v1-trips-id-questions-id-reply}
  /api/v1/replies/{reply_id}: {$ref: resources/trip.yaml#/paths/api-v1-replies-id}
  /api/v1/questions/{question_id}: {$ref: resources/trip.yaml#/paths/api-v1-questions-id}
  /api/v1/applications: {$ref: resources/application.yaml#/paths/api-v1-applications}
  /api/v1/applications/{_id}: {$ref: resources/application.yaml#/paths/api-v1-applications-id}
  /api/v1/applications/{_id}/pay: {$ref: resources/application.yaml#/paths/api-v1-applications-id-pay}
  /api/v1/applications/{_id}/cancel: {$ref: resources/application.yaml#/paths/api-v1-applications-id-cancel}
  /api/v1/finders: {$ref: resources/finder.yaml#/paths/api-v1-finders}
  /api/v1/finders/{_id}: {$ref: resources/finder.yaml#/paths/api-v1-finders-id}
  /api/v1/config: {$ref: resources/configuration.yaml#/paths/api-v1-config}
  /api/v1/dashboard: {$ref: resources/dashboard.yaml#/paths/api-v1-dashboard}



components:
  securitySchemes:
    apikey:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-acl-config:
        $ref: ./acl.yaml
  schemas:
    actor: {$ref: resources/actor.yaml#/schemas/actor}
    sponsorship: {$ref: resources/sponsorship.yaml#/schemas/sponsorship}
    trip: {$ref: resources/trip.yaml#/schemas/trip}
    application: {$ref: resources/application.yaml#/schemas/application}
    finder: {$ref: resources/finder.yaml#/schemas/finder}
    configuration: {$ref: resources/configuration.yaml#/schemas/configuration}
    dashboard: {$ref: resources/dashboard.yaml#/schemas/dashboard}
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
      additionalProperties: true